# Port for ppod to listen for the POST request that github sends
# WARN: Must be the same as on Github (check docs)
port=9000
# Endpoint to listen for the POST request that github sends
# Must be the same as on Github (check docs)
endpoint="/webhooks"
# Path to the script
# WARN: MUST BE EXECUTABLE (chmod +x /path/to/executable.sh)
# WARN: Give absolute path (/path/to/executable.sh instead of ../relative/path/to/executable.sh)
path_to_deployment_script="./tests/test_run.sh"
# Must be the same as on Github (check docs)
# IMPORTANT: KEEP SECRET
secret=test
# If the deploy script should be ran everytime ppod is first started
predeploy=true